name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies from Pipfile
        working-directory: web-service
        run: pipenv install --deploy --system

      - name: Run Flask app in background
        working-directory: web-service
        run: |
          python predict.py &
          sleep 5

      - name: Run test script
        working-directory: web-service
        run: python test.py

      - name: Build Docker image
        working-directory: web-service
        run: docker build -t duration-predictor .